# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=255)),
                ('post_text', models.CharField(max_length=10000)),
                ('post_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
