# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20161214_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_user',
            field=models.CharField(default=datetime.datetime(2016, 12, 14, 17, 38, 14, 109269, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
