# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20161214_2052'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post1',
        ),
    ]
