# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20161214_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_name',
            field=models.CharField(default=datetime.datetime(2016, 12, 15, 6, 43, 5, 547604, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
